### ISSUE TITLE
Import is empty

### ISSUE THREAD

**Issue by mwdhont** [hammar/RdfTranslationAddIn#23]
Hi @hammar,

I tried this tool to get our extension of REC in Excel, but it turns out that even with the original 'full.rdf', as taken from the REC-github, the tool gives me just an empty window. Printscreen and trial file attached. Any pointers what could be the reason for this?

![afbeelding](https://user-images.githubusercontent.com/53975317/166906351-d63e8866-3fc2-461e-8c71-968f40b6e500.png)
https://github.com/RealEstateCore/rec/blob/master/ontology/full.rdf

**Comment by hammar** [comment]
Hi,

The tool doesn't parse owl:imports statements, and REC Full is basically just a stub that imports all the child REC modules using owl:imports (which is why it is so small). To use REC Full it with this tool you'd have to merge all of those modules into one joint RDF file before loading it in the plugin.

Note that last time I looked at this code was several years back; there are bound to be some rough edges (particularly given the footgun nature of the OWL language itself, where the same basic node-edge-node construct could be modelled in many different ways). Specifically, I don't recall whether the code parses property restrictions on classes properly. All the same, it might be useful for providing an initial skeleton that one then extends with whatever is missing..

Best,

Karl
